name: Release

on:
  push:
    branches: [main, alpha, beta, rc]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release:
    name: Release
    if: github.repository_owner == 'TanStack'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0
      - name: Setup Tools
        uses: tanstack/config/.github/setup@main
      - name: Build
        run: pnpm build
      - name: Test Unit
        run: pnpm test:unit
      - name: Install Playwright Chrome
        run: pnpm --filter @tanstack/cli exec playwright install --with-deps chrome
      - name: E2E Blocking
        run: pnpm --filter @tanstack/cli test:e2e
      - name: Run Changesets (version or publish)
        uses: changesets/action@v1.5.3
        with:
          version: pnpm run changeset:version
          publish: pnpm run changeset:publish
          commit: "ci: Version Packages"
          title: "ci: Version Packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Comment on PRs about release
        if: steps.changesets.outputs.published == 'true'
        uses: tanstack/config/.github/comment-on-release@main
        with:
          published-packages: ${{ steps.changesets.outputs.publishedPackages }}
